### ISSUE TITLE
Cant see Allure build step - TeamCity 9.1.6 on Centos 5.9 server.

### ISSUE THREAD

**Issue by Drenadan** [allure-framework/allure-teamcity#40]
Have a problem with allure on Teamcity 9.1.6 on Centos 5.9.
Latest version allure-teamcity-plugin 2.3 was installed to TeamCity_Data Directory/plugins and allure-commandline 1.4.22 installed to TeamCity_Data Directory/plugins/.tools.
in teamcity plugin list allure is displayed like External plugins Installed - http://s015.radikal.ru/i331/1603/6a/c9063d88de56.png
But nothing from allure not displayed in build step list.http://s017.radikal.ru/i401/1603/1a/26a66510ad3e.png

**Comment by eroshenkoam** [comment]
fixed in 2.5
