### ISSUE TITLE
Agent does not have Allure Report build runner

### ISSUE THREAD

**Issue by Silwest** [allure-framework/allure-teamcity#63]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Incompatible runner: Allure Report

https://github.com/allure-framework/allure-teamcity/issues/62
1) After installing allure-teamcity plugin indeed you can configure build step as `Allure Report` however you'll get `Incompatible runner: Allure Report` when trying to run the build
2) After checking the issue mentioned above and executing the same scenario now we don't even asee `Allure Report` in the list of steps.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Just install allrue-teamcity plugin.

#### What is the expected behavior?
Allure report should be available for our use.

#### What is the motivation / use case for changing the behavior?
Current behavior is wrong. 

#### Please tell us about your environment:

| Allure version | 2.3.5 |
| 2017.1.2 (build 46812 | RedHat |

#### Other information 
https://github.com/allure-framework/allure-teamcity/issues/62
1) After installing allure-teamcity plugin indeed you can configure build step as `Allure Report` however you'll get `Incompatible runner: Allure Report` when trying to run the build
2) After checking the issue mentioned above and executing the same scenario now we don't even asee `Allure Report` in the list of steps.

**Comment by eroshenkoam** [comment]
First of all you need to install allure-teamcity plugin from here: 
https://dl.bintray.com/qameta/generic/io/qameta/allure/allure-teamcity/2.6/allure-teamcity-2.6.zip

After that you need to configure allure-commanline:
* Download the latest version of allure zip archive from here
* Rename archive from allure-.zip to allure-commandline.zip
* Upload allure-commandline.zip to team city in Administrations/Tools settings

I think it helps you.

**Comment by vbragin** [comment]
@Silwest Feel free to reopen the issue if the solution doesn't help.
