### ISSUE TITLE
Parameter for report artifact subdirectory is ignored

### ISSUE THREAD

**Issue by KillAChicken** [allure-framework/allure-teamcity#65]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Add a build step for allure report and specify allure_report as a report artifact subdirectory.
New report is generated, but the artifacts are published to the root directory.

#### What is the expected behavior?
The artifacts are published to the directory allure_report.

#### What is the motivation / use case for changing the behavior?
Issue is related to https://github.com/allure-framework/allure-teamcity/pull/37 and https://github.com/allure-framework/allure-teamcity/issues/34

#### Please tell us about your environment:
allure-teamcity@2.6

#### Other information 
It seems that the proper behavior could be implemented by specifying user input explicitly in the method afterProcessSuccessfullyFinished of the class [AllureBuildServiceAdapter](https://github.com/allure-framework/allure-teamcity/blob/e73406f0f313c184af62b00c39f31f5185578842/allure-teamcity-agent/src/main/java/io/qameta/allure/teamcity/AllureBuildServiceAdapter.java#L199)
As far as I understand, something like
`artifactsWatcher.addNewArtifactsPath(reportDirectory.toString() + " => " + getRunnerParameters().get(REPORT_PATH_PREFIX));`
should do the trick.

**Comment by alexKazarin** [comment]
Same problem. 
Allure teamcity plugin: 2.4.1
