### ISSUE TITLE
Link to previous builds in trend are incorrect

### ISSUE THREAD

**Issue by cakeinpanic** [allure-framework/allure-teamcity#67]
allure plugin: 2.4.1
allure: 2.6

Take a look at url and at executors panel. Ids are different. Seems that allure tracks builds in its own way
<img width="1435" alt="screenshot 2017-12-18 11 58 27" src="https://user-images.githubusercontent.com/588916/34097851-82053b5c-e3eb-11e7-93cf-17f8d4366149.png">

Link in executors tab leads to teamcity correctly, but links to builds from trends are broken, cause they use these inner ids

Also links to builds from History tab on testcase view lead to correct builds

**Comment by eroshenkoam** [comment]
I will fix it in the end of the week

**Comment by dzaiats** [comment]
Hello! Any updates on this issue?

**Comment by eroshenkoam** [comment]
@dzaiats Seems like you miss teamcity url in administration settings 
<img width="1003" alt="2018-09-09 16 03 41" src="https://user-images.githubusercontent.com/781455/45264753-02104380-b44a-11e8-9a60-954e216aa873.png">
