### ISSUE TITLE
Default setting throws error JAVA_HOME unset & JAVA settings seem to be dead fields

### ISSUE THREAD

**Issue by michalfita** [allure-framework/allure-teamcity#68]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

##### Allure via TeamCity plugin without enforcing JAVA_HOME set
Regardless of setting in the plugin settings form in TC 2017.2.2, the allure plugin throws an error:
![obraz](https://user-images.githubusercontent.com/4925040/37430483-265d628e-27ca-11e8-8aa4-01e1240d4371.png)

##### Allure TeamCity plugin settings form
![obraz](https://user-images.githubusercontent.com/4925040/37429716-1946ce5c-27c8-11e8-8979-8001dcb0f0af.png)
These last three fields doesn't seem to work - nothing in plugin source code suggests their existence, so there has to be JetBrains' addition for certain types of plugins.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Install TeamCity 2017.2.2
2. Install build agent on Windows 10 without extra JAVA installed
3. Install `allure-teamcity-2.6.zip` into a `plugin` directory and `allure-commandline.zip` into `.tools`
4. Create configuration with ability to generate allure reports (we're using behave)
5. In your configuration add Allure build step
6. Run the build

##### Allure via TeamCity plugin without enforcing JAVA_HOME set
There should be defaults to pick up by alure as `%env.TEAMCITY_JRE%` is always set to the agent's own Java.

##### Allure TeamCity plugin settings form
Would be nice to get these Java settings sorted one way or another.
- Remove them and put in manual how to set `JAVA_HOME` using Parameters for Configuration.
- Make them work (better option)

#### What is the motivation / use case for changing the behavior?
The current configuration form is misleading if the Allure on the agent doesn't work regardless of these settings.

To make it work the following Parameter in configuration is required:
![obraz](https://user-images.githubusercontent.com/4925040/37431294-c1f2f892-27cc-11e8-8c22-bf241b53df3a.png)

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | behave@1.2.6 |
| Allure adaptor | allure-behave@2.3.2b1 |
| Generate report using | allure-teamcity@2.6 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by eroshenkoam** [comment]
I will fix it in the end of the week

**Comment by eroshenkoam** [comment]
https://github.com/allure-framework/allure-teamcity/pull/93
