### ISSUE TITLE
Link to Allure in overview

### ISSUE THREAD

**Issue by Qloriti** [allure-framework/allure-teamcity#69]
Artem promised to add link to Allure. 🤔 

![image](https://user-images.githubusercontent.com/19430143/37836797-7920ad86-2ec4-11e8-81e5-564be3670018.png)

Probably, to make this case transparent:
http://automated-testing.info/t/teamcity-agent-ne-rabotaet-s-allure-plaginom/14924/2
👌

**Comment by eroshenkoam** [comment]
done https://github.com/allure-framework/allure-teamcity/releases/tag/2.8.1
