### ISSUE TITLE
History of previous builds in trend are not added if you branch=<default>

### ISSUE THREAD

**Issue by maksmi** [allure-framework/allure-teamcity#72]
Hello, 
it seems that allure does not see history of previous build for branch name = \<default> 
![allure](https://user-images.githubusercontent.com/1764932/42081027-0b426f82-7b8d-11e8-9aab-c8ba4a82c235.png)
![allurelog](https://user-images.githubusercontent.com/1764932/42081031-1245f61e-7b8d-11e8-8eea-bbb48ae3b96f.png)

for named branches it seems working ok 

 allure-teamcity 2.5

**Comment by eroshenkoam** [comment]
please, use 2.8.1 version of plugin
