### ISSUE TITLE
Migrationg build to plugin 2.8 has problem

### ISSUE THREAD

**Issue by TheKnight** [allure-framework/allure-teamcity#74]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
After updating Teamcity Allure plugin to 2.8 old builds not started with unmet requirements on agents "allure.publish.mode: The property value should not be empty".

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1) Create build with Allure Teamcity plugin v2.7 or older.
2) Update plugin to 2.8

#### What is the expected behavior?
Old builds automaticaly set default value for publish mode when plugin will be updated.

#### Please tell us about your environment:
| Generate report using | allure-teamcity@2.8 |

**Comment by eroshenkoam** [comment]
fixed https://github.com/allure-framework/allure-teamcity/releases/tag/2.8.1
