### ISSUE TITLE
"Allure history information missing" no previous execution history 

### ISSUE THREAD

**Issue by VladimirKovalenko** [allure-framework/allure-teamcity#79]
- [x] bug report

When TeamCity generate allure report it cannot reach history files from previous builds.
The message is "Allure history information missing in..."
TeamCity log
![image](https://user-images.githubusercontent.com/3935708/46857133-eb765700-ce10-11e8-8a2b-50ddd071a44b.png)

When I open links to history in browser I'm able to download current build history (because current build is last finished)

I found kind of the same bug here
https://github.com/allure-framework/allure-teamcity/issues/72
But in my case I have check it with version 2.9 and 2.8.1. The same issue for both.
![image](https://user-images.githubusercontent.com/3935708/46857291-46a84980-ce11-11e8-8165-1333c7c023bb.png)

I use the latest command line version allure-2.7.0.zip
![image](https://user-images.githubusercontent.com/3935708/46857420-8cfda880-ce11-11e8-9cfc-599d8b79bb9e.png)

After reinstalling allure-teamcity I always restart teamcity and recreate Build step. This is my configuration.
![image](https://user-images.githubusercontent.com/3935708/46858080-2a0d1100-ce13-11e8-9132-5528e5a23477.png)

| allure-teamcity | 2.8.1 |
| allure-comandline | 2.7 |

**Comment by sergei-homich** [comment]
I have the same problem - no trends for <default> branch. <default> branch appears if build uses several VCS. Please fix it.

**Comment by komorran** [comment]
Same problem. Please fix it, because solution for this issue isn't obvious
