### ISSUE TITLE
TeamCity 9.1.7 cannot see Allure Report in Build Steps after installing

### ISSUE THREAD

**Issue by adrian-brown** [allure-framework/allure-teamcity#84]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ x] bug report

#### What is the current behavior?
Installed the allure-teamcity and allure-command line to TeamCity 9.17.  
I see the Plugin correctly under Administration / External plugins:
<TeamCity Data Directory>/.unpacked/allure-teamcity-2.9.0
I see the plugin available under Diagnostics / Browse Data Directory:
allure-teamcity-2.9.0.zip 
I see the build agents have been made available under Agent Parameters / Configuration Parameters:
teamcity.tool.allure-commandline | C:\BuildAgent\tools\allure-commandline

What I don't see (after a server reboot) is the Build Step for the `Allure Report`.  I had changed the zip file as per recommendations.  

Logs on TeamCity:

```[2019-03-25 10:13:59,654]   WARN -   jetbrains.buildServer.SERVER - Agent 'ip_xx.xx.xx.xx' attempts to register build runner(s) [allureReportGeneratorRunner] which are not registered on the server. Check server installation is not corrupted or related plugins register build runners (run types) on the server correctly.```

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

I cannot see the `Allure Report` to be able to run it

#### What is the expected behavior?

To see the `Allure Report` in the Build Step

#### What is the motivation / use case for changing the behavior?

None, I want to use the reporter.

#### Please tell us about your environment:

| --- | --- |
| Test framework | webdriverio@4.14.3 |
| Generate report using | allure-teamcity@2.9.0 |
| Allure version | 2.9.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by adrian-brown** [comment]
Also TC is running Java 1.7.

**Comment by adrian-brown** [comment]
Does TC need a complete reboot or just a restart to see the Build Step option appear?  I can see the build agents have the Allure reporter under the `tools` directory on the buildAgents

**Comment by adrian-brown** [comment]
Since I cannot setup TC in the way the plugin is, how’s about just running the node version instead with allure generate to create the allure-report would that work? And would TC serve up the index.html in the same way? I’m guessing this is the same wrapper to build the report or am I wrong?  It would be easy to do the above as a post running tests as a command line build step.  Please do let me know.

**Comment by eroshenkoam** [comment]
@adrian-brown Did you install allure-commandline tool?
Like here: https://docs.qameta.io/allure/#_teamcity

**Comment by adrian-brown** [comment]
Sure did. I see the build agents have been updated correctly and no errors in the build agents log. Teamcity server has the plugin correctly.  What should I show you to help diagnose? Is the idea of running the node version an option?  How does the index.html serve up on TC just works by clicking on it?

**Comment by adrian-brown** [comment]
I've managed to use the commandline (node) as a post build step, and show the report on a new tab, however I don't benefit from the historical trend, is there a way to enable that correctly as the checkout process will destroy the folder each time.  IS making the plugin work the only way to secure this @eroshenkoam or you know how to?

**Comment by adrian-brown** [comment]
Ideally I would like to use the plugin, but cant get it to show in the build steps, please tell me what you need to see for debug @eroshenkoam

**Comment by adrian-brown** [comment]
Resolved getting history, bit of a faff but sorted.  I'll leave this open to see if its possible to use the plugin, till then I'm up and running with lots of workarounds
