### ISSUE TITLE
Add support TeamCity 2019.1

### ISSUE THREAD

**Issue by ekho** [allure-framework/allure-teamcity#86]
#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Plugin can not find allure-commandline tool

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
- Install TeamCity 2019.1
- Install Plugin
- Install allure-commandline.zip with TeamCity admin webui
- Create build configuration with build step Allure Report
- See that no one agents can run this build

#### What is the expected behavior?
Build started

#### Please tell us about your environment:

| Allure version | 2.12.1 |
| --- | --- |
| TeamCity | 2019.1 |
| Generate report using | allure-teamcity@2.9.0 |

#### Other information 

Root cause is that Allure Report trying to find allure-commandline tool on agent start. But in TeamCity 2019.1 agents download tools from the server only when starting the first build that requests these tools. [WhatsNewinTeamCity2019.1](https://www.jetbrains.com/help/teamcity/what-s-new-in-teamcity-2019-1.html#WhatsNewinTeamCity2019.1-Fasteragentsupgrade), [Issue in tracker](https://youtrack.jetbrains.com/issue/TW-60737)

**Comment by vbragin** [comment]
I've checked on TeamCity 2020.2 looks like it works now

**Comment by derom** [comment]
Doesn't work in teamcity 2022.10
